# Change these first
owner: pionyr # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Pionyr.cz
    url: https://pionyr.cz/
  - name: RISP
    url: https://risp.pionyr.cz/RISP/MainForm.wgx
  - name: Mozaika
    url: https://mozaika.pionyr.cz/
  - name: Praha.pionyr.cz
    url: https://praha.pionyr.cz/
  - name: Praha.pionyr.cz (static status)
    url: https://praha.pionyr.cz/status.html
  - name: Praha.pionyr.cz (dynamic status)
    url: https://praha.pionyr.cz/status.php
  - name: Ledová města
    url: https://ledovamesta.pionyr.cz/
  - name: Ledová Praha
    url: https://ledovapraha.cz/
  - name: Děti dětem
    url: https://detidetem.pionyr.cz/
  - name: Babi dědo
    url: https://babidedo.pionyr.cz/
  - name: Pionýrské fórum
    url: https://forum.pionyr.cz/
  - name: Pionýrská kuchařka
    url: https://kucharka.pionyr.cz/
  - name: Lvicata.cz (not hosted by Pionýr) # Non-pionyr website, used as a benchmark
    url: https://www.lvicata.cz/

skipTopicsUpdate: true
skipDeleteIssues: true
workflowSchedule:
  responseTime: "0 */1 * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://pionyr.cz/wp-content/themes/pionyr/img/web/logo.svg
  name: Pionýr status
  introTitle: Current status of Pionýr webpages
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
